services:
    netgen_tags.field_type.eztags.converter:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Tags
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: eztags }

    netgen_tags.field_type.eztags.storage_gateway:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage\Gateway\DoctrineStorage
        arguments:
            - "@ibexa.persistence.connection"
            - "@Ibexa\\Contracts\\Core\\Persistence\\Content\\Language\\Handler"

    netgen_tags.api.storage_engine.legacy.handler.tags.mapper:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Mapper
        arguments:
            - "@Ibexa\\Contracts\\Core\\Persistence\\Content\\Language\\Handler"
            - "@Ibexa\\Core\\Persistence\\Legacy\\Content\\Language\\MaskGenerator"

    netgen_tags.api.storage_engine.legacy.handler.tags.gateway.inner:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Gateway\DoctrineDatabase
        arguments:
            - "@ibexa.persistence.connection"
            - "@Ibexa\\Contracts\\Core\\Persistence\\Content\\Language\\Handler"
            - "@Ibexa\\Core\\Persistence\\Legacy\\Content\\Language\\MaskGenerator"

    netgen_tags.api.storage_engine.legacy.handler.tags.gateway.exception_conversion:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Gateway\ExceptionConversion
        arguments:
            - "@netgen_tags.api.storage_engine.legacy.handler.tags.gateway.inner"

    netgen_tags.api.storage_engine.legacy.handler.tags:
        class: Netgen\TagsBundle\Core\Persistence\Legacy\Tags\Handler
        arguments:
            - "@netgen_tags.api.storage_engine.legacy.handler.tags.gateway.exception_conversion"
            - "@netgen_tags.api.storage_engine.legacy.handler.tags.mapper"
