netgen_tags_admin_synonym_add_select:
    path: /add/{mainTagId}
    controller: netgen_tags.admin.controller.synonym:addSynonymSelectAction
    methods: [GET, POST]

netgen_tags_admin_synonym_add:
    path: /add/{mainTagId}/{languageCode}
    controller: netgen_tags.admin.controller.synonym:addSynonymAction
    methods: [GET, POST]
