services:
    netgen_tags.field_type.eztags:
        class: Netgen\TagsBundle\Core\FieldType\Tags\Type
        parent: ezpublish.fieldType
        arguments:
            - "@netgen_tags.api.service.tags"
            - "@ibexa.config.resolver"
        tags:
            - { name: ibexa.field_type, alias: eztags }

    netgen_tags.field_type.eztags.external_storage:
        class: Netgen\TagsBundle\Core\FieldType\Tags\TagsStorage
        arguments:
            - "@netgen_tags.field_type.eztags.storage_gateway"
            - "@netgen_tags.api.service.tags"
        tags:
            - { name: ibexa.field_type.storage.external.handler, alias: eztags }

    netgen_tags.field_type.eztags.indexable:
        class: Netgen\TagsBundle\Core\FieldType\Tags\SearchField
        tags:
            - { name: ibexa.field_type.indexable, alias: eztags }

    netgen_tags.field_type.eztags.form_mapper:
        class: Netgen\TagsBundle\Core\FieldType\Tags\FormMapper
        arguments:
            - "@ibexa.config.resolver"
        tags:
            - { name: ibexa.admin_ui.field_type.form.mapper.definition, fieldType: eztags }
            - { name: ibexa.admin_ui.field_type.form.mapper.value, fieldType: eztags }
