services:
    netgen_tags.pagerfanta.related_content_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\RelatedContentAdapter
        arguments:
            - "@netgen_tags.api.service.tags"
            - "@ibexa.config.resolver"

    netgen_tags.pagerfanta.children_tags_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\ChildrenTagsAdapter
        arguments:
            - "@netgen_tags.api.service.tags"
            -
    netgen_tags.pagerfanta.search_tags_adapter:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\SearchTagsAdapter
        arguments:
            - "@netgen_tags.api.service.tags"

    netgen_tags.pagerfanta.view.netgen_tags_admin:
        class: Netgen\TagsBundle\Core\Pagination\Pagerfanta\View\TagsAdminView
        # Not being lazy results in out of memory exceptions on Ibexa Platform 2.0,
        # probably due to @twig dependency
        lazy: true
        arguments:
            - "@twig"
            - "%netgen_tags.admin.default_pager_template%"
        tags:
            - { name: pagerfanta.view, alias: netgen_tags_admin }
