netgen_tags_rest:
    resource: "routing/rest.yaml"
    prefix: "%ibexa.rest.path_prefix%"

netgen_tags_internal:
    resource: "routing/internal.yaml"

netgen_tags_admin_redirects:
    resource: "routing/admin/redirects.yaml"
    prefix: /tags

netgen_tags_admin:
    resource: "routing/admin.yaml"
    prefix: /tags/admin
