services:
    netgen_tags.templating.twig.extension:
        class: Netgen\TagsBundle\Templating\Twig\Extension\NetgenTagsExtension
        tags:
            - { name: twig.extension }

    netgen_tags.templating.twig.runtime:
        class: Netgen\TagsBundle\Templating\Twig\Extension\NetgenTagsRuntime
        arguments:
            - "@netgen_tags.api.service.tags"
            - "@ibexa.api.service.language"
            - "@ibexa.api.service.content_type"
        tags:
            - { name: twig.runtime }
