services:
    netgen_tags.validator.tag_create_struct:
        class: Netgen\TagsBundle\Validator\Structs\TagCreateStructValidator
        tags:
            - { name: validator.constraint_validator, alias: netgen_tags_tag_create_struct }

    netgen_tags.validator.tag_update_struct:
        class: Netgen\TagsBundle\Validator\Structs\TagUpdateStructValidator
        tags:
            - { name: validator.constraint_validator, alias: netgen_tags_tag_update_struct }

    netgen_tags.validator.synonym_create_struct:
        class: Netgen\TagsBundle\Validator\Structs\SynonymCreateStructValidator
        arguments:
            - "@netgen_tags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: netgen_tags_synonym_create_struct }

    netgen_tags.validator.tag:
        class: Netgen\TagsBundle\Validator\TagValidator
        arguments:
            - "@netgen_tags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: netgen_tags_tag }

    netgen_tags.validator.language:
        class: Netgen\TagsBundle\Validator\LanguageValidator
        arguments:
            - "@ibexa.api.service.language"
        tags:
            - { name: validator.constraint_validator, alias: netgen_tags_language }

    netgen_tags.validator.remote_id:
        class: Netgen\TagsBundle\Validator\RemoteIdValidator
        arguments:
            - "@netgen_tags.api.service.tags"
        tags:
            - { name: validator.constraint_validator, alias: netgen_tags_remote_id }
