services:
    netgen_tags.view.builder_parameter_collector.current_page:
        class: Netgen\TagsBundle\View\Builder\ParametersFilter\CurrentPage
        tags:
            - { name: kernel.event_subscriber }

    netgen_tags.view.view_parameters_injector.related_content_pager:
        class: Netgen\TagsBundle\View\ParametersInjector\RelatedContentPager
        arguments:
            - "@netgen_tags.pagerfanta.related_content_adapter"
            - "@ibexa.config.resolver"
        tags:
            - { name: kernel.event_subscriber }

    netgen_tags.view.cache_response_listener:
        class: Netgen\TagsBundle\View\Response\CachedViewResponseListener
        arguments:
            - "@fos_http_cache.http.symfony_response_tagger"
            - "@ibexa.config.resolver"
        tags:
            - { name: kernel.event_subscriber }

    netgen_tags.view.tag_view_builder:
        class: Netgen\TagsBundle\View\Builder\TagViewBuilder
        arguments:
            - "@netgen_tags.api.service.tags"
            - "@Ibexa\\Core\\MVC\\Symfony\\View\\Configurator\\ViewProvider"
            - "@Ibexa\\Core\\MVC\\Symfony\\View\\ParametersInjector\\EventDispatcherInjector"
            - "@ibexa.config.resolver"
            - "@security.authorization_checker"
        tags:
            - { name: ibexa.view.builder }

    netgen_tags.view.tag_matcher_factory:
        class: Netgen\TagsBundle\Matcher\TagMatcherFactory
        arguments:
            - "@ibexa.api.repository"
            - "@netgen_tags.api.service.tags"
            - "@ibexa.config.resolver"
            - "@service_container"

    netgen_tags.view.tag_view_provider:
        class: Netgen\TagsBundle\View\Provider\TagViewProvider
        arguments:
            - "@netgen_tags.view.tag_matcher_factory"
        tags:
            - { name: ibexa.view.provider, type: 'Netgen\TagsBundle\View\TagView', priority: 10 }
