services:
    netgen_tags.search.solr.query.common.criterion_visitor.tag_id:
        class: Netgen\TagsBundle\Core\Search\Solr\Query\Common\CriterionVisitor\Tags\TagId
        arguments:
            - "@Ibexa\\Core\\Search\\Common\\FieldNameResolver"
            - "@Ibexa\\Core\\Search\\Common\\FieldValueMapper"
            - "@Ibexa\\Contracts\\Core\\Persistence\\Content\\Type\\Handler"
            - "eztags"
            - "tag_ids"
        tags:
            - { name: ibexa.search.solr.query.content.criterion.visitor }
            - { name: ibexa.search.solr.query.location.criterion.visitor }

    netgen_tags.search.solr.query.common.criterion_visitor.tag_keyword:
        class: Netgen\TagsBundle\Core\Search\Solr\Query\Common\CriterionVisitor\Tags\TagKeyword
        arguments:
            - "@Ibexa\\Core\\Search\\Common\\FieldNameResolver"
            - "@Ibexa\\Core\\Search\\Common\\FieldValueMapper"
            - "@Ibexa\\Contracts\\Core\\Persistence\\Content\\Type\\Handler"
            - "eztags"
            - "tag_keywords"
        tags:
            - { name: ibexa.search.solr.query.content.criterion.visitor }
            - { name: ibexa.search.solr.query.location.criterion.visitor }

    netgen_tags.search.solr.query.common.sort_clause_visitor.content_type_id:
        class: Netgen\TagsBundle\Core\Search\Solr\Query\Common\SortClauseVisitor\ContentTypeId
        tags:
            - { name: ibexa.search.solr.query.content.sort_clause.visitor }
